# Generated by Django 4.0.4 on 2022-05-03 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('password', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passwords',
            old_name='desciption',
            new_name='description',
        ),
    ]
