# Generated by Django 3.2.13 on 2022-05-03 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20220504_0047'),
        ('password', '0002_rename_desciption_passwords_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwords',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_profile.tags'),
        ),
        migrations.AlterField(
            model_name='passwords',
            name='category',
            field=models.CharField(choices=[('ENT', 'Entertainment'), ('LER', 'Learning'), ('SHO', 'Shopping'), ('PAY', 'Payment')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='passwords',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_profile.site'),
        ),
    ]
