# Generated by Django 4.0.4 on 2022-05-12 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_alter_profile_user_alter_site_user_alter_tags_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('password', '0003_auto_20220504_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwords',
            name='email',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='passwords',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passwords', to='user_profile.site'),
        ),
        migrations.AlterField(
            model_name='passwords',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passwords', to='user_profile.tags'),
        ),
        migrations.AlterField(
            model_name='passwords',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passwords', to=settings.AUTH_USER_MODEL),
        ),
    ]
