# Generated by Django 3.2.13 on 2022-05-12 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('password', '0004_alter_passwords_email_alter_passwords_site_and_more'),
        ('password', '0004_auto_20220511_2237'),
    ]

    operations = [
    ]
