# Generated by Django 3.2.13 on 2022-05-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password', '0005_merge_20220512_2131'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passwords',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='passwords',
            name='category',
            field=models.CharField(blank=True, choices=[('ENT', 'Entertainment'), ('LER', 'Learning'), ('SHO', 'Shopping'), ('PAY', 'Payment')], max_length=300, null=True),
        ),
    ]
