# Generated by Django 3.2.13 on 2022-05-15 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_rename_is_public_site_is_private'),
        ('password', '0006_auto_20220515_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwords',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passwords', to='user_profile.site'),
        ),
        migrations.AlterField(
            model_name='passwords',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passwords', to='user_profile.tags'),
        ),
    ]
