# Generated by Django 3.2.13 on 2022-05-12 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_alter_profile_user_alter_site_user_alter_tags_user'),
        ('user_profile', '0003_auto_20220511_2237'),
    ]

    operations = [
    ]
