# Generated by Django 3.2.13 on 2022-05-15 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_merge_20220512_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='is_public',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
